/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package upe.resource;

import org.junit.jupiter.api.Test;
import upe.resource.model.UpeDialogState;
import upe.resource.persistorimpl.UpeDialogPersistorJdbcImpl;

import java.sql.Connection;

import static org.junit.jupiter.api.Assertions.*;

public class UpePersistorTests {
    @Test
    public void testConnection() throws Exception {
        Connection con  = UpeDialogPersistorJdbcImpl.intance().getConnection();
        assertNotNull(con);
    }

    @Test
    public void testInitiate() throws Exception {
        UpeDialogState state = UpeDialogPersistorJdbcImpl.intance().initiate();
        assertNotNull(state);
        assertNotNull(state.getDialogID());
        UpeDialogState state2 = UpeDialogPersistorJdbcImpl.intance().initiate();
        assertNotNull(state2);
        assertNotNull(state2.getDialogID());
        assertNotEquals(state.getDialogID(), state2.getDialogID());
    }

    @Test
    public void testStepInsertion() throws Exception {
        UpeDialogState state = UpeDialogPersistorJdbcImpl.intance().initiate();
        assertNotNull(state);
        state = UpeDialogPersistorJdbcImpl.intance().storeStep(state.getDialogID(), state.getStepCount(), "/login", null, "xgadcsp");
        state = UpeDialogPersistorJdbcImpl.intance().storeStep(state.getDialogID(), state.getStepCount()+1, "/pwd", null, "s****t");
        state = UpeDialogPersistorJdbcImpl.intance().storeAction(state.getDialogID(), state.getStepCount()+1, "/actLogin");
        UpeDialogState state2 = UpeDialogPersistorJdbcImpl.intance().restore(state.getDialogID());
        assertNotNull(state2);
        assertEquals(state.getDialogID(), state2.getDialogID());
        assertTrue(state2.getSteps().size()==3);
    }
}
