/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package upe.resource;

import com.google.gson.Gson;
import org.junit.jupiter.api.Test;
import upe.resource.model.UpeDialogState;
import upe.resource.persistorimpl.UpeDialogPersistorJdbcImpl;

import java.sql.Connection;

import static org.junit.jupiter.api.Assertions.*;

public class UpePersistorTests {
    @Test
    public void testConnection() throws Exception {
        Connection con  = UpeDialogPersistorJdbcImpl.intance(UpeDialog.getGson()).getConnection();
        assertNotNull(con);
    }

    @Test
    public void testInitiate() throws Exception {
        UpeDialogState state = UpeDialogPersistorJdbcImpl.intance(UpeDialog.getGson()).initiate();
        assertNotNull(state);
        assertNotNull(state.getDialogID());
        UpeDialogState state2 = UpeDialogPersistorJdbcImpl.intance(UpeDialog.getGson()).initiate();
        assertNotNull(state2);
        assertNotNull(state2.getDialogID());
        assertNotEquals(state.getDialogID(), state2.getDialogID());
    }
/*
    @Test
    public void testStepInsertion() throws Exception {
        Gson gson = new Gson();
        UpeDialogState state = UpeDialogPersistorJdbcImpl.intance(UpeDialog.getGson()).initiate();
        assertNotNull(state);
        state = UpeDialogPersistorJdbcImpl.intance(UpeDialog.getGson()).storeValueChange(state.getDialogID(), state.getStepCount(), "/login", null, "xgadcsp", "");
        state = UpeDialogPersistorJdbcImpl.intance(UpeDialog.getGson()).storeValueChange(state.getDialogID(), state.getStepCount()+1, "/pwd", null, "s****t", "");
        state = UpeDialogPersistorJdbcImpl.intance(UpeDialog.getGson()).storeAction(state.getDialogID(), state.getStepCount()+1, "/actLogin", "");
        UpeDialogState state2 = UpeDialogPersistorJdbcImpl.intance(UpeDialog.getGson()).restore(state.getDialogID());
        assertNotNull(state2);
        assertEquals(state.getDialogID(), state2.getDialogID());
        assertTrue(state2.getSteps().size()==3);
    }

 */
}
